version: "3.9"

services:
  redis:
    image: redis:6.2
    container_name: chatbot-cache-1
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", ""]
    volumes:
      - chatbot_cache:/data
    restart: unless-stopped

  bot:
    build: .
    container_name: chatbot-app
    volumes:
      - .:/app
    ports:
      - "8070:8070"  
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  api-gateway:
    image: nginx:latest
    container_name: chatbot-api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bot

volumes:
  chatbot_cache:

