name: Docker Build & Deploy to Azure VM

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx (optional)
      uses: docker/setup-buildx-action@v2


    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
        script: |
          cd /home/noopyuser/Noopy-Bot

          echo "📥 Pulling latest code..."
          git pull origin main

          echo "🛑 Stopping and removing running containers..."
          docker compose down || true
          docker rm -f $(docker ps -aq) || true

          echo "🧼 Removing all Docker images..."
          docker rmi -f $(docker images -aq) || true

          echo "🧹 Removing all Docker volumes..."
          docker volume rm $(docker volume ls -q) || true

          echo "🔌 Removing all Docker networks (except default)..."
          docker network prune -f || true

          echo "🧽 Pruning Docker build cache..."
          docker builder prune -af || true

          echo "🚀 Rebuilding and starting containers..."
          docker compose up -d --build
